spring:
  application:
    name: SmartVoyagerAI
  ai:
#    ollama:
#      chat:
#        options:
#          model: llama3.2
#        model: ollama
#      base-url: http://localhost:11434
    openai:
      api-key: ${OPENAPI_KEY}
      base-url: https://openrouter.ai/api
      chat:
        options:
          model: openai/gpt-4o


  mail:
    host: smtp.gmail.com
    port: 587
    username: general.azhar.u.azad@gmail.com
    password: ${EMAIL_APP_PASS}
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true

weatherapi:
  key: ${WEATHERAPI_KEY}

amadeus:
  grant-type: ${GRANT_TYPE}
  client-id: ${CLIENT_ID}
  client-secret: ${CLIENT_SECRET}

